name: ai-readi-notebooks
channels:
  - defaults
  - conda-forge
dependencies:
  - python = 3.12.0
  - ipykernel = 6.29.5
  - openpyxl = 3.1.5
  - ipywidgets
  - pip
  - pip:
      - pandas == 2.2.3
      - matplotlib == 3.10.0
      - pydicom == 3.0.1
      - pillow == 11.1.0
      - tqdm == 4.67.1 
      - wfdb == 4.2.0
      - pre-commit == 4.2.0
      - chardet == 5.2.0
